### ISSUE TITLE
latest npm release fails to install

### ISSUE THREAD

**Issue by keithchilders** [mcavage/node-bunyan-syslog#11]
Greetings,

gypnpm ERR! bunyan-syslog@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bunyan-syslog@0.2.2 install script.
npm ERR! This is most likely a problem with the bunyan-syslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bunyan-syslog
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\Keith\Projects\test
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm

Working around it for now, would love to re-adopt if you get it patched :)

**Comment by mcavage** [comment]
0.3.0 published
