### ISSUE TITLE
OSX /var/log/system.log only gets msgs from Level >= 'warn'

### ISSUE THREAD

**Issue by alexander-daniel** [mcavage/node-bunyan-syslog#18]
I don't have much testing to help you out with just yet, but I noticed that 'info' and 'debug' dosen't work on OSX. When I spun up an Ubuntu 14.04 box, it worked out of the box.

Thanks for the great module! I'll try to see whats up with this, but maybe you're aware.

Cheers!

**Comment by nicokaiser** [comment]
The default `/etc/asl.conf` (as of OS X 10.10) says:

```
# save everything from emergency to notice
? [<= Level notice] store
```

The `notice` level is above the `info` level in syslog (and thus, Bunyan), so `info` records are not stored by the default configuration.

**Comment by alexander-daniel** [comment]
@nicokaiser awesome, thanks for the answer, that makes total sense! Cheers!
